defaults:
  - _self_


algo_name: drqv2_tog


agent:
  _target_: src.agents.drqv2_tog.DrQv2TogAgent
  obs_dim: ???
  action_dim: ???
  device: ???

  lr: ${lr}
  critic_target_tau: 0.01
  update_every_steps: 2
  hidden_dim: 1024
  feature_dim: ${feature_dim}
  stddev_schedule: ${stddev_schedule}
  stddev_clip: 0.3

  use_bc: ${use_bc}
  bc_weight: ${bc_weight}

  augmentation: ${augmentation}
  dropblock: ${dropblock}
