defaults:
  - _self_


algo_name: iql


agent:
  _target_: src.agents.iql.IQLAgent
  obs_dim: ???
  action_dim: ???
  device: ???

  lr: ${lr}
  critic_target_tau: 0.01
  update_every_steps: 2
  hidden_dim: 1024
  feature_dim: ${feature_dim}
  stddev_schedule: ${stddev_schedule}
  stddev_clip: 0.3

  use_bc: False
  bc_weight: 0.0

  augmentation: ${augmentation}
  dropblock: 0.0

  iql_scale: 3.0
  iql_expectile: 0.7
  schedule_T_max: 1000000
